
import "bootstrap/dist/css/bootstrap.css";
import './globals.css'

import Header from './components/header'
import Footer from './components/footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body>
        <div className="cover-container d-flex h-100 p-3 mx-auto flex-column">
          <header className="masthead mb-auto">
            <Header />
          </header>
          
          <main role="main" className="inner cover">
            {children}
          </main>
          
          <footer className="mastfoot mt-auto">
            <Footer />
          </footer>
          
      </div>
        
      </body>
    </html>
  )
}
